[package]
name = "en-local-proto"
version = "0.0.1"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
discord-rich-presence = "1"
igd-next = "0.18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
png = "0.17"
libloading = "0.8"
cpal = "0.15"
sdl3 = { version = "0.20", features = ["build-from-source-static"] }
windows = { version = "0.58", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_Threading",
  "Win32_System_JobObjects",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Com",
  "Win32_UI_Shell",
  "Win32_UI_Shell_Common",
  "Win32_Media_Audio",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Variant",
  "Win32_NetworkManagement_IpHelper",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_System_SystemInformation",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
] }
